version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_windows_1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - main-bridge

networks:
  main-bridge:
    driver: bridge

volumes:
  ollama:
